version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./:/app
    environment:
      APP_ID: $APP_ID
      APP_CODE: $APP_CODE
  db:
    image: postgres
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
