version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./:/app
  db:
    image: postgres
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
